### ISSUE TITLE
Очень страшная функция

### ISSUE THREAD

**Issue by gvino** [temikfart/2sem---informatics#2]
https://github.com/temikfart/2sem---informatics/blob/af26ecf1247ebc764414b8c3961c9ad2b46e120e/pdp-11/pr/pdp_run.c#L16

Я бы эту штуку распилил на функции, для каждой моды -- своя. Узнал моду -- дернул нужную. Когда функция не лезет в экран -- это очень-очень грустно.

Пример из кровавого ынтерпрайза: у нас линтер ругается на функции длиннее 15 строк.

**Comment by temikfart** [comment]
Теперь не страшная. Не длиннее 15 строк это сильно.
