### ISSUE TITLE
Потенциально лишний код

### ISSUE THREAD

**Issue by gvino** [temikfart/2sem---informatics#4]
https://github.com/temikfart/2sem---informatics/blob/af26ecf1247ebc764414b8c3961c9ad2b46e120e/pdp-11/pr/pdp_run.c#L73

Какую функциональную нагрузку несет эта проверка?

**Comment by temikfart** [comment]
Согласен, убрал. Думал, что если раньше узнаю, что ничего проверять не нужно, то сэкономлю :) Мало ли параметров этих много будет.
