### ISSUE TITLE
Лишний комментарий.

### ISSUE THREAD

**Issue by gvino** [temikfart/2sem---informatics#5]
https://github.com/temikfart/2sem---informatics/blob/af26ecf1247ebc764414b8c3961c9ad2b46e120e/pdp-11/pr/pdp_run.c#L82

Не захламляй код лишними комментариями. Если ты это отладил и дебаг здесь тебе не нужен -- удаляй. Или оставь и запускай с логлевелом TRACE, тогда оно и так не отобразится.

**Comment by temikfart** [comment]
Убрал.
