### ISSUE TITLE
Лишний экспорт?

### ISSUE THREAD

**Issue by gvino** [temikfart/2sem---informatics#6]
https://github.com/temikfart/2sem---informatics/blob/af26ecf1247ebc764414b8c3961c9ad2b46e120e/pdp-11/pr/pdp.h#L49

Зачем ты экспортируешь эту переменную? Ты же ее передаешь как параметр в do-функцию, глобально она у тебя никуда не упала.

**Comment by temikfart** [comment]
Поправил.
